version: "3.7"

services:
  timescale:
    image: timescale/timescaledb:latest-pg12
    container_name: timescale2
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=sarscov2
      - POSTGRES_PASSWORD=sarscov2
      - POSTGRES_DB=sarscov2
    volumes:
      - ./db/db.sql:/docker-entrypoint-initdb.d/init.sql
  # web:
  #   build: .
  #   command: uvicorn web.main:app --host 0.0.0.0 --port 80 --reload
  #   volumes:
  #     - .:/app
  #   ports:
  #     - "8000:80"
  #   depends_on:
  #     - timescale
    
